#!/bin/bash
shopt -s lastpipe
declare -A owned
pacman -Qlq | grep '^/etc' | while read file;do
    owned["$file"]=1
done
find /etc -wholename /etc/ca-certificates/extracted -prune -or -type f -and -not -name '*~' -print0 | while read -d '' file;do
    [[ -z ${owned["$file"]} ]] && echo "$file"
done
